#!/usr/bin/env python3
"""Extract first paragraph and H1 from notes/lessonN.html and write a JS file.

Output: assets/js/lecture_summaries.js containing two arrays:
- lectureTitlesZh (from H1)
- lectureSummariesZh (first <p> after the header)
"""
import glob, os, re
from html import unescape

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
NOTES_DIR = os.path.join(ROOT, 'notes')
OUT_DIR = os.path.join(ROOT, 'assets', 'js')
os.makedirs(OUT_DIR, exist_ok=True)

def extract(path):
    t = open(path, 'r', encoding='utf-8').read()
    # extract H1
    h1 = ''
    m = re.search(r'<h1>(.*?)</h1>', t, flags=re.S|re.I)
    if m:
        h1 = re.sub(r'\s+', ' ', m.group(1)).strip()
    # extract first paragraph after the H1 (first <p> after h1)
    # find position of h1
    summary = ''
    try:
        pos = m.end()
        rest = t[pos:]
        p = re.search(r'<p>(.*?)</p>', rest, flags=re.S|re.I)
        if p:
            summary = re.sub(r'<[^>]+>', '', p.group(1)).strip()
            summary = re.sub(r'\s+', ' ', summary)
    except Exception:
        pass
    return h1, summary

files = sorted(glob.glob(os.path.join(NOTES_DIR, 'lesson*.html')))
titles = []
summaries = []
for f in files:
    h1, s = extract(f)
    titles.append(h1)
    summaries.append(s)

out_path = os.path.join(OUT_DIR, 'lecture_summaries.js')
with open(out_path, 'w', encoding='utf-8') as f:
    f.write('// auto-generated by scripts/extract_note_summaries.py\n')
    f.write('const lectureTitlesZh = ' + repr(titles) + ';\n')
    f.write('const lectureSummariesZh = ' + repr(summaries) + ';\n')

print('Wrote', out_path)
